# Generated by Django 4.1 on 2022-08-19 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='in_menu',
            field=models.BooleanField(default=False),
        ),
    ]
