# Generated by Django 4.1 on 2022-08-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_page_in_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='menu_label',
            field=models.CharField(default='a', max_length=40),
            preserve_default=False,
        ),
    ]
