# Generated by Django 4.1 on 2022-08-19 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_page_menu_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
