# Generated by Django 4.1 on 2022-08-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_page_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['-weight']},
        ),
        migrations.AddField(
            model_name='page',
            name='weight',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
