# Generated by Django 4.1 on 2022-08-23 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_page_options_page_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
