# Generated by Django 4.1 on 2022-08-18 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pubref', '0001_initial'),
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markdown', models.TextField(default='')),
                ('html', models.TextField(default='')),
                ('valid', models.BooleanField(default=False)),
                ('error', models.TextField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_posts', to='posts.post')),
                ('publications', models.ManyToManyField(to='pubref.publication')),
                ('submissions', models.ManyToManyField(related_name='posts', to='assignments.submission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
