# Generated by Django 4.1 on 2022-09-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_root'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='root',
        ),
        migrations.AddField(
            model_name='post',
            name='ancestors',
            field=models.ManyToManyField(blank=True, related_name='descendents', to='posts.post'),
        ),
    ]
