# Generated by Django 4.1 on 2022-08-18 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, max_length=40, unique=True)),
                ('bibtex', models.TextField()),
                ('apa_html', models.TextField()),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
    ]
