# Generated by Django 4.1 on 2022-08-19 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pubref', '0002_publication_contributor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['apa_html']},
        ),
    ]
