# Generated by Django 4.1 on 2022-08-19 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubref', '0003_alter_publication_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['apa_text']},
        ),
        migrations.AddField(
            model_name='publication',
            name='apa_text',
            field=models.TextField(default='x'),
            preserve_default=False,
        ),
    ]
