# Generated by Django 4.1 on 2022-08-29 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pubref', '0004_alter_publication_options_publication_apa_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('upload', models.FileField(upload_to='publications/')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='pubref.publication')),
            ],
        ),
    ]
