# Generated by Django 4.1 on 2022-08-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubref', '0005_publicationfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationfile',
            name='mime',
            field=models.CharField(default='application/pdf', max_length=100),
        ),
    ]
