# Generated by Django 4.1 on 2022-08-29 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pubref', '0006_publicationfile_mime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicationfile',
            options={'ordering': ['description']},
        ),
    ]
