# Generated by Django 4.1 on 2022-11-02 22:40

from django.db import migrations, models
import pubref.models


class Migration(migrations.Migration):

    dependencies = [
        ('pubref', '0007_alter_publicationfile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='slug',
            field=models.CharField(db_index=True, max_length=40, unique=True, validators=[pubref.models.validate_slug]),
        ),
    ]
