# Generated by Django 4.1 on 2022-08-20 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewer_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reviews.reviewerrole'),
        ),
    ]
