# Generated by Django 4.1 on 2022-08-20 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0008_alter_submission_mime_alter_submission_upload'),
        ('reviews', '0003_review_reviewer_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewerrole',
            name='assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_roles', to='assignments.assignment'),
        ),
    ]
