# Generated by Django 4.1 on 2022-09-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_reviewerrole_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewerrole',
            name='status',
            field=models.CharField(choices=[('0', 'Not started'), ('1', 'Waiting for review'), ('4', 'Waiting for teacher review'), ('2', 'Waiting for new submission'), ('3', 'Complete')], default='0', max_length=1),
        ),
    ]
