# Generated by Django 4.1 on 2022-08-18 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pubref', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markdown', models.TextField(default='')),
                ('html', models.TextField(default='')),
                ('valid', models.BooleanField(default=False)),
                ('error', models.TextField(null=True)),
                ('is_teacher', models.BooleanField(default=False)),
                ('publications', models.ManyToManyField(to='pubref.publication')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
