# Generated by Django 4.1 on 2022-08-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_is_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_frequency',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('NEVER', 'Never')], default='WEEKLY', max_length=20),
        ),
    ]
