# Generated by Django 4.1 on 2022-09-08 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_email_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_frequency',
        ),
    ]
