# Generated by Django 4.1 on 2022-08-19 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['due_date']},
        ),
        migrations.AddField(
            model_name='assignment',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
