# Generated by Django 4.1 on 2022-08-20 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_alter_assignment_options_assignment_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='peer_review',
            field=models.BooleanField(default=False),
        ),
    ]
