# Generated by Django 4.1 on 2022-08-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_assignment_peer_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='slug',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
