# Generated by Django 4.1 on 2022-08-20 17:05

import assignments.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_alter_assignment_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='upload',
            field=models.FileField(upload_to=assignments.models.upload_filename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'odt']), assignments.models.check_file_size]),
        ),
    ]
