# Generated by Django 4.1 on 2022-08-20 17:20

import assignments.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_alter_submission_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='upload',
            field=models.FileField(upload_to=assignments.models.upload_filename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'odt', 'txt', 'rtf']), assignments.models.check_file_size, assignments.models.check_mime_type]),
        ),
    ]
