# Generated by Django 4.1 on 2022-08-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_alter_submission_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='mime',
            field=models.CharField(default='x', max_length=200),
            preserve_default=False,
        ),
    ]
