# Generated by Django 4.1 on 2022-08-20 19:00

import assignments.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0007_submission_mime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='mime',
            field=models.CharField(max_length=200, validators=[assignments.models.check_mime_type]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='upload',
            field=models.FileField(upload_to=assignments.models.upload_filename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'odt', 'txt', 'rtf']), assignments.models.check_file_size]),
        ),
    ]
