# Generated by Django 4.1 on 2022-08-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0008_alter_submission_mime_alter_submission_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='has_submissions',
            field=models.BooleanField(default=True),
        ),
    ]
