# Generated by Django 4.1 on 2022-08-29 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0009_assignment_has_submissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('upload', models.FileField(upload_to='examples/')),
                ('mime', models.CharField(default='application/pdf', max_length=100)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='assignments.assignment')),
            ],
            options={
                'ordering': ['description'],
            },
        ),
    ]
