# Generated by Django 4.1 on 2022-08-29 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0010_assignmentsubmission'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssignmentSubmission',
            new_name='AssignmentExample',
        ),
    ]
